/* --- database.js --- */
const aiDatabase = [
    // --- 1. PRE-DESIGN ---
    {
        id: "microsoft_copilot",
        name: "Microsoft Copilot",
        provider: "Microsoft",
        website_url: "https://www.microsoft.com/en-us/microsoft-365/copilot",
        logo_url: "Recourses/Logos/copilot.png", // Ensure you have placeholders or real paths
        description_short: "Integrated AI in Word/Excel to summarize briefs.",
        description_long: "Microsoft Copilot is an AI-powered digital assistant that aims to provide personalized assistance to users for a range of tasks and activities. It integrates with Microsoft 365 apps like Word, Excel, PowerPoint, Outlook, and Teams.",
        integration_type: "Integrated",
        host_software: "M365",
        primary_function: "Text/Code/Regs",
        input_type: "Text",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 30.00,
        usage_limit_per_month: -1, // Unlimited
        company_size_fit: ["Studio", "Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Ecosystem native", "Secure", "Familiar UI"],
        cons: ["Generalist model", "Requires M365 Sub"],
        efficiency_text: "Reduces brief analysis time by 40%.",
        workflow_text: "Runs directly inside Word sidebar."
    },
    {
        id: "digital_blue_foam",
        name: "Digital Blue Foam",
        provider: "DBF",
        website_url: "https://www.digitalbluefoam.com/",
        description_short: "Web-based generative design for sustainable feasibility.",
        description_long: "A web-based generative design tool that helps architects and planners create sustainable building designs. It uses AI to analyze data and generate optimal design solutions based on user constraints.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "Data",
        output_type: "3D Model",
        pricing_model: "Subscription",
        price_base_monthly: 150.00, // Est
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 7,
        pros: ["Sustainability focus", "Fast feasibility"],
        cons: ["Web-only", "Export limitations"],
        efficiency_text: "Generates feasibility studies in minutes vs days.",
        workflow_text: "Export massing to Rhino/Revit via plugin."
    },
    {
        id: "crosby_studios",
        name: "Crosby Studios",
        provider: "Crosby",
        website_url: "https://crosbystudios.com/",
        description_short: "Generative interior design concepts.",
        description_long: "An AI tool focused on avant-garde interior design and furniture concepts, often characterized by bold colors and unique geometries.",
        integration_type: "Service",
        primary_function: "Image/Video Gen",
        input_type: "Text",
        output_type: "Image",
        pricing_model: "Freemium",
        price_base_monthly: 0,
        usage_limit_per_month: 50,
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 6,
        pros: ["Aesthetic focus", "Unique style"],
        cons: ["Niche use", "Low control"],
        efficiency_text: "Rapid moodboarding.",
        workflow_text: "Web interface generation."
    },
    {
        id: "reimagine_home",
        name: "ReimagineHome",
        provider: "Reimagine AI",
        website_url: "https://www.reimaginehome.ai/",
        description_short: "AI for virtual staging and renovation ideas.",
        description_long: "Specializes in virtual staging, remodeling, and landscaping visualizations using AI to overlay new designs on existing photos.",
        integration_type: "Service",
        primary_function: "Image/Video Gen",
        input_type: "Image",
        output_type: "Image",
        pricing_model: "Freemium",
        price_base_monthly: 0, 
        usage_limit_per_month: 30,
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 7,
        pros: ["Instant renovation ideas", "Easy to use"],
        cons: ["2D only", "Generic styles"],
        efficiency_text: "Instant visual options for clients.",
        workflow_text: "Upload photo -> Select Style -> Generate."
    },
    {
        id: "testfit",
        name: "TestFit",
        provider: "TestFit Inc.",
        website_url: "https://www.testfit.io/",
        description_short: "Real-time generative feasibility and zoning.",
        description_long: "The ultimate building configurator. TestFit generates solves for multifamily, industrial, and subdivision layouts in milliseconds based on parametric constraints.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "Data",
        output_type: "3D Model",
        pricing_model: "Enterprise",
        price_base_monthly: 400.00, // High cost annual
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Instant yield calc", "Deal closing speed"],
        cons: ["Parametric constraints", "High Cost"],
        efficiency_text: "Reduces feasibility phase from 2 weeks to 2 hours.",
        workflow_text: "Desktop app -> Export to Revit/DXF."
    },
    {
        id: "upcodes_copilot",
        name: "UpCodes Copilot",
        provider: "UpCodes",
        website_url: "https://up.codes/",
        description_short: "AI assistant for building codes.",
        description_long: "An AI research assistant tailored for building codes. It helps architects find relevant code sections and answers compliance questions.",
        integration_type: "Service",
        primary_function: "Text/Code/Regs",
        input_type: "Text",
        output_type: "Text",
        pricing_model: "Subscription",
        price_base_monthly: 59.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Instant code answers", "Source linking"],
        cons: ["US/Code specific", "Liability risk"],
        efficiency_text: "Cuts code research time by 70%.",
        workflow_text: "Web query -> Copy/Paste to Report."
    },
    {
        id: "autodesk_forma",
        name: "Autodesk Forma",
        provider: "Autodesk",
        website_url: "https://www.autodesk.com/eu/products/forma",
        description_short: "Real-time environmental analysis & site planning.",
        description_long: "Cloud-based software for early-stage planning. It provides conceptual design capabilities, predictive analytics, and automations.",
        integration_type: "Integrated",
        host_software: "Revit",
        primary_function: "Data Interpretation",
        input_type: "3D Model",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 180.00, // Approx part of AEC
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Revit interoperability", "Cloud analysis"],
        cons: ["Subscription cost", "Generic forms"],
        efficiency_text: "Real-time analysis feedback.",
        workflow_text: "Browser based -> Send to Revit."
    },
    {
        id: "polycam",
        name: "Polycam",
        provider: "Polycam",
        website_url: "https://poly.cam/",
        description_short: "LiDAR scanning app for site context.",
        description_long: "The leading 3D scanning app for iPhone and Android. Uses LiDAR and Photogrammetry to create 3D models from the real world.",
        integration_type: "Tool",
        primary_function: "Reality Capture",
        input_type: "Image",
        output_type: "3D Model",
        pricing_model: "Freemium",
        price_base_monthly: 15.00, // Pro sub
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Firm"],
        benchmark_rating: 9,
        pros: ["Fast site context", "Easy to use"],
        cons: ["Phone hardware dep.", "Mesh topology messy"],
        efficiency_text: "Site survey to 3D model in < 1 hour.",
        workflow_text: "Mobile Scan -> Cloud Process -> OBJ Download."
    },
    {
        id: "archistar",
        name: "Archistar",
        provider: "Archistar.ai",
        website_url: "https://www.archistar.ai/",
        description_short: "Property intelligence for zoning compliance.",
        description_long: "Combines architectural design with artificial intelligence to help find profitable development sites and assess feasibility.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 99.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 7,
        pros: ["Regulatory data", "Investment focus"],
        cons: ["Region specific (AUS)", "Cost"],
        efficiency_text: "Instant zoning check.",
        workflow_text: "Web map interface."
    },
    {
        id: "aurivus",
        name: "Aurivus",
        provider: "Aurivus",
        website_url: "https://aurivus.com/",
        description_short: "AI processing for point clouds to BIM.",
        description_long: "AI that automatically structures and models point clouds into BIM objects.",
        integration_type: "Tool",
        primary_function: "Reality Capture",
        input_type: "3D Model",
        output_type: "BIM",
        pricing_model: "Pay-per-use",
        price_base_monthly: 0,
        usage_limit_per_month: 0, // Pay per scan
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Scan-to-BIM automation", "High accuracy"],
        cons: ["Complex setup", "Cost per sqft"],
        efficiency_text: "80% reduction in modeling time.",
        workflow_text: "Upload Point Cloud -> Download Revit Model."
    },

    // --- 2. SCHEMATIC DESIGN ---
    {
        id: "stable_diffusion",
        name: "Stable Diffusion",
        provider: "Stability AI",
        website_url: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
        description_short: "Local generative AI for unlimited image generation.",
        description_long: "Open-source text-to-image model. When run locally (e.g., Automatic1111), it offers unlimited generation, ControlNet precision, and zero cost.",
        integration_type: "Tool",
        primary_function: "Image/Video Gen",
        input_type: "Text",
        output_type: "Image",
        pricing_model: "Free",
        price_base_monthly: 0,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Boutique"],
        benchmark_rating: 9,
        pros: ["Privacy/Zero Cost", "ControlNet"],
        cons: ["Requires powerful GPU", "Technical setup"],
        efficiency_text: "Unlimited iteration speed.",
        workflow_text: "Local WebUI -> Import to Photoshop."
    },
    {
        id: "midjourney",
        name: "Midjourney",
        provider: "Midjourney Inc.",
        website_url: "https://www.midjourney.com/",
        description_short: "AI-driven atmospheric concept art.",
        description_long: "The industry leader for high-fidelity, artistic AI image generation. Best for early stage mood and concept.",
        integration_type: "Service",
        primary_function: "Image/Video Gen",
        input_type: "Text",
        output_type: "Image",
        pricing_model: "Subscription",
        price_base_monthly: 10.00,
        usage_limit_per_month: 200, // approx
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 10,
        pros: ["Pure inspiration", "Best-in-class aesthetics"],
        cons: ["Non-technical", "Discord interface"],
        efficiency_text: "Concept art in seconds.",
        workflow_text: "Discord / Web -> Download."
    },
    {
        id: "adobe_firefly",
        name: "Adobe Firefly",
        provider: "Adobe",
        website_url: "https://www.adobe.com/sensei/generative-ai/firefly.html",
        description_short: "Generative fill integrated into Photoshop.",
        description_long: "Adobe's family of creative generative AI models, integrated directly into Photoshop for Generative Fill and Expand.",
        integration_type: "Integrated",
        host_software: "Photoshop",
        primary_function: "Image/Video Gen",
        input_type: "Image",
        output_type: "Image",
        pricing_model: "Subscription",
        price_base_monthly: 20.00, // CC cost
        usage_limit_per_month: 500, // Generative credits
        company_size_fit: ["Freelancer", "Studio", "Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Workflow seamless", "Commercial safe"],
        cons: ["Less 'creative' models", "Censorship"],
        efficiency_text: "Seamless post-production.",
        workflow_text: "In-canvas selection -> Generate."
    },
    {
        id: "lookx",
        name: "LookX",
        provider: "LookX",
        website_url: "https://www.lookx.ai/",
        description_short: "AI tailored for architecture renderings.",
        description_long: "An AI rendering platform trained specifically on architectural datasets, allowing for better control over building forms than generalist models.",
        integration_type: "Service",
        primary_function: "Image/Video Gen",
        input_type: "3D Model",
        output_type: "Image",
        pricing_model: "Subscription",
        price_base_monthly: 15.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 7,
        pros: ["Architect-centric", "Model upload"],
        cons: ["Learning curve", "Web interface"],
        efficiency_text: "Render-like quality without rendering engines.",
        workflow_text: "Upload massing -> Select Style -> Render."
    },
    {
        id: "hypar",
        name: "Hypar",
        provider: "Hypar",
        website_url: "https://hypar.io/",
        description_short: "Open platform for modular building generators.",
        description_long: "A cloud platform for generating building systems. Users can combine logic 'functions' to create complex BIM outcomes.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "Data",
        output_type: "3D Model",
        pricing_model: "Freemium",
        price_base_monthly: 75.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 7,
        pros: ["Modular logic", "Open source functions"],
        cons: ["Web-based", "Coding required for custom logic"],
        efficiency_text: "Automates repetitive system layouts.",
        workflow_text: "Web setup -> Stream to Revit."
    },
    {
        id: "wallacei",
        name: "Wallacei",
        provider: "Wallacei",
        website_url: "https://www.wallacei.com/",
        description_short: "Evolutionary engine for multi-objective optimization.",
        description_long: "An evolutionary simulation engine for Grasshopper 3D, designed to help users optimize designs through genetic algorithms.",
        integration_type: "Integrated",
        host_software: "Rhino/GH",
        primary_function: "Data Interpretation",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Free",
        price_base_monthly: 0,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 8,
        pros: ["Data visualization", "Deep analytic control"],
        cons: ["Steep learning curve", "Rhino dependent"],
        efficiency_text: "Finds optimal solutions among thousands.",
        workflow_text: "Grasshopper Plugin."
    },
    {
        id: "finch_3d",
        name: "Finch 3D",
        provider: "Finch",
        website_url: "https://finch3d.com/",
        description_short: "Graph-based generative design for plans.",
        description_long: "Generative technology that helps architects generate floor plans adapted to constraints in seconds. Features bidirectional streaming to Rhino/Revit.",
        integration_type: "Integrated",
        host_software: "Rhino/GH",
        primary_function: "CAD/BIM/Technical",
        input_type: "3D Model",
        output_type: "3D Model",
        pricing_model: "Subscription",
        price_base_monthly: 50.00, // Estimated
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 8,
        pros: ["Optimization logic", "Interactive editing"],
        cons: ["Beta access", "Limited availability"],
        efficiency_text: "Solves floor plan tetris instantly.",
        workflow_text: "Plugin + Web Interface."
    },
    {
        id: "snaptrude",
        name: "Snaptrude",
        provider: "Snaptrude",
        website_url: "https://www.snaptrude.com/",
        description_short: "Collaborative browser-based BIM.",
        description_long: "Often called 'Figma for BIM'. It enables real-time collaboration on building design directly in the browser with automated parametric modeling features.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "Data",
        output_type: "BIM",
        pricing_model: "Subscription",
        price_base_monthly: 100.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Google Docs for BIM", "Fast massing"],
        cons: ["New ecosystem", "Not full CD capable yet"],
        efficiency_text: "Rapid collaborative concepting.",
        workflow_text: "Browser -> Revit Export."
    },
    {
        id: "planfinder",
        name: "PlanFinder",
        provider: "PlanFinder",
        website_url: "https://www.planfinder.xyz/",
        description_short: "Plugin to generate apartment layouts.",
        description_long: "A plugin for Rhino, Grasshopper, and Revit that automatically generates floor plans based on room requirements and outer boundaries.",
        integration_type: "Integrated",
        host_software: "Revit/Rhino",
        primary_function: "CAD/BIM/Technical",
        input_type: "3D Model",
        output_type: "3D Model",
        pricing_model: "Subscription",
        price_base_monthly: 20.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 8,
        pros: ["Direct plugin", "Fast variations"],
        cons: ["Residential only", "Rigid logic"],
        efficiency_text: "Unit layouts in seconds.",
        workflow_text: "Draw boundary -> Click Generate."
    },
    {
        id: "rayon",
        name: "Rayon",
        provider: "Rayon",
        website_url: "https://www.rayon.so/",
        description_short: "Collaborative space planning tool.",
        description_long: "A web-based 2D CAD tool designed for speed and collaboration. Features 'smart' blocks and lightweight AI assistance.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "Image",
        output_type: "Image",
        pricing_model: "Freemium",
        price_base_monthly: 15.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 7,
        pros: ["Fast 2D workflow", "Great UI"],
        cons: ["2D focused", "Not BIM"],
        efficiency_text: "Faster than AutoCAD for quick studies.",
        workflow_text: "Browser based CAD."
    },
    {
        id: "krea_ai",
        name: "Krea.ai",
        provider: "Krea",
        website_url: "https://www.krea.ai/",
        description_short: "Real-time AI upscaling and enhancement.",
        description_long: "Known for its real-time generative canvas and high-quality upscaling capabilities.",
        integration_type: "Service",
        primary_function: "Image/Video Gen",
        input_type: "3D Model",
        output_type: "Image",
        pricing_model: "Freemium",
        price_base_monthly: 24.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 8,
        pros: ["Instant enhancement", "Real-time painting"],
        cons: ["Cloud dependent", "Subscription"],
        efficiency_text: "Low-res inputs to High-res outputs instantly.",
        workflow_text: "Screen capture -> AI Enhance."
    },
    {
        id: "veras",
        name: "Veras (EvolveLAB)",
        provider: "EvolveLAB",
        website_url: "https://www.evolvelab.io/veras",
        description_short: "AI rendering plugin inside Revit/Rhino.",
        description_long: "An AI powered visualization app that uses your 3D model geometry as a substrate for generative imagery. Runs directly inside Revit.",
        integration_type: "Integrated",
        host_software: "Revit/Rhino",
        primary_function: "Image/Video Gen",
        input_type: "BIM",
        output_type: "Image",
        pricing_model: "Subscription",
        price_base_monthly: 49.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 8,
        pros: ["In-model rendering", "Geometry fidelity"],
        cons: ["Abstract results", "Subscription cost"],
        efficiency_text: "Rendering without leaving BIM.",
        workflow_text: "Revit View -> Render."
    },
    {
        id: "enscape",
        name: "Enscape",
        provider: "Chaos",
        website_url: "https://enscape3d.com/",
        description_short: "Real-time rendering workflow.",
        description_long: "A commercial real-time rendering and virtual reality plugin. It is the industry standard for instant BIM visualization.",
        integration_type: "Integrated",
        host_software: "Revit/Rhino",
        primary_function: "Image/Video Gen",
        input_type: "BIM",
        output_type: "Image",
        pricing_model: "Subscription",
        price_base_monthly: 50.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Instant visuals", "Easy setup"],
        cons: ["High-end GPU req.", "Price"],
        efficiency_text: "Zero export time required.",
        workflow_text: "Live sync window."
    },
    {
        id: "d5_render",
        name: "D5 Render",
        provider: "D5 Techs",
        website_url: "https://www.d5render.com/",
        description_short: "Local real-time renderer with AI atmosphere.",
        description_long: "A real-time ray tracing renderer that uses AI for denoising and atmosphere generation. High quality free version available.",
        integration_type: "Tool",
        primary_function: "Image/Video Gen",
        input_type: "3D Model",
        output_type: "Image",
        pricing_model: "Freemium",
        price_base_monthly: 30.00, // Pro
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Firm"],
        benchmark_rating: 9,
        pros: ["Raytracing quality", "Community assets"],
        cons: ["Hardware intensive", "Standalone app"],
        efficiency_text: "Faster than Lumion/V-Ray.",
        workflow_text: "Sync plugin -> Standalone render."
    },
    {
        id: "arkio",
        name: "Arkio",
        provider: "Arkio",
        website_url: "https://www.arkio.is/",
        description_short: "Collaborative VR design.",
        description_long: "A collaborative design tool for VR, AR, tablets and phones. Sketch on top of Revit models or site maps.",
        integration_type: "Tool",
        primary_function: "CAD/BIM/Technical",
        input_type: "3D Model",
        output_type: "3D Model",
        pricing_model: "Freemium",
        price_base_monthly: 60.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 7,
        pros: ["Immersive design", "Multi-user"],
        cons: ["VR headset needed", "Low precision"],
        efficiency_text: "Spatial understanding improved.",
        workflow_text: "VR Headset session."
    },

    // --- 3. DESIGN DEVELOPMENT ---
    {
        id: "skema",
        name: "Skema",
        provider: "Skema",
        website_url: "https://www.skema.ai/",
        description_short: "Concept to BIM automation.",
        description_long: "Reuses your past successful designs to automate the creation of new BIM models. Morph conceptual masses into detailed Revit LOD 300 models.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "3D Model",
        output_type: "BIM",
        pricing_model: "Enterprise",
        price_base_monthly: 200.00, // Quote based
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Rapid BIM creation", "Knowledge reuse"],
        cons: ["Revit dependent", "Setup required"],
        efficiency_text: "Weeks of modeling done in minutes.",
        workflow_text: "Web setup -> Revit Plugin."
    },
    {
        id: "bricscad_bim",
        name: "BricsCAD BIM",
        provider: "Bricsys",
        website_url: "https://www.bricsys.com/bricscad-bim",
        description_short: "AI-driven BIM classification.",
        description_long: "A DWG-based BIM tool that uses AI (BIMify) to automatically classify loose 3D geometry into IFC compliant BIM elements.",
        integration_type: "Tool",
        primary_function: "CAD/BIM/Technical",
        input_type: "3D Model",
        output_type: "BIM",
        pricing_model: "Subscription",
        price_base_monthly: 120.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 7,
        pros: ["Smart classification", "Perpetual license option"],
        cons: ["Market share", "Learning curve"],
        efficiency_text: "Automates 'dumb' geometry to BIM.",
        workflow_text: "Standalone application."
    },
    {
        id: "augmenta",
        name: "Augmenta",
        provider: "Augmenta",
        website_url: "https://www.augmenta.ai/",
        description_short: "AI for automated electrical design.",
        description_long: "Generative design platform specifically for electrical conduit routing and systems.",
        integration_type: "Integrated",
        host_software: "Revit",
        primary_function: "CAD/BIM/Technical",
        input_type: "BIM",
        output_type: "BIM",
        pricing_model: "Subscription",
        price_base_monthly: 100.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Systems automation", "Collision free"],
        cons: ["Specialized (MEP)", "Cost"],
        efficiency_text: "Routes complex systems automatically.",
        workflow_text: "Revit Plugin."
    },
    {
        id: "cove_tool",
        name: "Cove.tool",
        provider: "Cove.tool",
        website_url: "https://cove.inc/",
        description_short: "Automated energy & carbon analysis.",
        description_long: "Building performance simulation software that allows for rapid analysis of energy, daylight, glare, and carbon.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "BIM",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 100.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Speed/Validation", "Cost optimization"],
        cons: ["Separate platform", "US Centric defaults"],
        efficiency_text: "Analysis concurrent with design.",
        workflow_text: "Plugin export -> Web analysis."
    },
    {
        id: "one_click_lca",
        name: "One Click LCA",
        provider: "One Click LCA",
        website_url: "https://www.oneclicklca.com/",
        description_short: "Automated life-cycle carbon assessment.",
        description_long: "The world-leading end-to-end sustainability software platform for construction. Automates LCA from BIM models.",
        integration_type: "Integrated",
        host_software: "Revit",
        primary_function: "Data Interpretation",
        input_type: "BIM",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 250.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Sustainability std.", "Huge database"],
        cons: ["Data heavy", "Expensive"],
        efficiency_text: "Automated BOM to Carbon calc.",
        workflow_text: "Revit Plugin -> Cloud Report."
    },
    {
        id: "kaedim",
        name: "Kaedim",
        provider: "Kaedim",
        website_url: "https://www.kaedim3d.com/",
        description_short: "Convert 2D images into 3D models.",
        description_long: "Machine learning tool that converts 2D images into 3D CAD models automatically.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "Image",
        output_type: "3D Model",
        pricing_model: "Subscription",
        price_base_monthly: 150.00,
        usage_limit_per_month: 20, // Models
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 6,
        pros: ["Asset creation", "Fast"],
        cons: ["Not full BIM", "Topology varies"],
        efficiency_text: "Instant custom furniture assets.",
        workflow_text: "Upload Image -> Download OBJ."
    },
    {
        id: "adobe_substance_3d",
        name: "Adobe Substance 3D",
        provider: "Adobe",
        website_url: "https://www.adobe.com/products/substance3d-sampler.html",
        description_short: "AI photogrammetry for materials.",
        description_long: "Part of the Substance suite (Sampler), using AI to scan real world materials and convert them into PBR seamless textures.",
        integration_type: "Tool",
        primary_function: "Reality Capture",
        input_type: "Image",
        output_type: "Image",
        pricing_model: "Subscription",
        price_base_monthly: 50.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 9,
        pros: ["High fidelity mats", "Industry std"],
        cons: ["Part of Adobe suite", "GPU req"],
        efficiency_text: "Photo to PBR material in minutes.",
        workflow_text: "Desktop App."
    },
    {
        id: "stylib",
        name: "Stylib",
        provider: "Stylib",
        website_url: "https://www.stylib.com/",
        description_short: "AI product search engine.",
        description_long: "Visual search engine for architectural products. Upload an image of a mood and find real products that match.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Image",
        output_type: "Data",
        pricing_model: "Free", // Brand driven
        price_base_monthly: 0,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Firm"],
        benchmark_rating: 7,
        pros: ["Visual search", "Free"],
        cons: ["Inventory limited", "UK/EU focused"],
        efficiency_text: "Finds specifiable products instantly.",
        workflow_text: "Web search."
    },
    {
        id: "homestyler",
        name: "Homestyler",
        provider: "Easyhome",
        website_url: "https://www.homestyler.com/",
        description_short: "AI interior design & layout.",
        description_long: "Cloud based interior design tool with AI decoration features. Very popular for quick interior visualizations.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "2D",
        output_type: "3D Model",
        pricing_model: "Freemium",
        price_base_monthly: 20.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 7,
        pros: ["User friendly", "Good render engine"],
        cons: ["Not BIM native", "Consumer focused"],
        efficiency_text: "Rapid interior iteration.",
        workflow_text: "Browser based."
    },
    {
        id: "specright",
        name: "Specright",
        provider: "Specright",
        website_url: "https://www.specright.com/",
        description_short: "Specification data management.",
        description_long: "Specification Data Management software to manage supply chain data and specs.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Data",
        output_type: "Docs",
        pricing_model: "Enterprise",
        price_base_monthly: 500.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Data standard", "Supply chain logic"],
        cons: ["Setup time", "Mfg focused"],
        efficiency_text: "Centralized spec data.",
        workflow_text: "SaaS Platform."
    },
    {
        id: "deltek_specpoint",
        name: "Deltek Specpoint",
        provider: "Deltek",
        website_url: "https://www.deltek.com/en/architecture-and-engineering/specpoint",
        description_short: "Modern specification writing linked to BIM.",
        description_long: "Home of AIA MasterSpec. Connects specs to the Revit model for better coordination.",
        integration_type: "Integrated",
        host_software: "Revit",
        primary_function: "Management",
        input_type: "BIM",
        output_type: "Docs",
        pricing_model: "Subscription",
        price_base_monthly: 150.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["BIM integration", "MasterSpec content"],
        cons: ["Cost", "Legacy UI"],
        efficiency_text: "Coordinated specs reducing errors.",
        workflow_text: "Cloud Platform + Revit Plugin."
    },

    // --- 4. CONSTRUCTION DOCS ---
    {
        id: "solibri",
        name: "Solibri",
        provider: "Nemetschek",
        website_url: "https://www.solibri.com/",
        description_short: "Rule-based model checking.",
        description_long: "The gatekeeper for BIM quality. Automated clash detection and rule-based checking for compliance.",
        integration_type: "Tool",
        primary_function: "Data Interpretation",
        input_type: "BIM",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 200.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Deep audit capability", "Industry standard"],
        cons: ["Complex ruleset", "IFC based"],
        efficiency_text: "Automated QA/QC.",
        workflow_text: "Standalone App."
    },
    {
        id: "navisworks",
        name: "Navisworks",
        provider: "Autodesk",
        website_url: "https://www.autodesk.com/products/navisworks/overview",
        description_short: "Clash detection and 4D simulation.",
        description_long: "Project review software to coordinate BIM data. Standard for clash detection.",
        integration_type: "Tool",
        primary_function: "CAD/BIM/Technical",
        input_type: "BIM",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 120.00, // AEC Collection
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Industry standard", "Huge model support"],
        cons: ["Manual clash grouping", "Old codebase"],
        efficiency_text: "Conflict resolution before build.",
        workflow_text: "Standalone App."
    },
    {
        id: "swapp",
        name: "Swapp",
        provider: "Swapp",
        website_url: "https://swapp.ai/",
        description_short: "Automates construction documents.",
        description_long: "AI platform that automates the entire CD phase from a design model. Claims to do months of work in days.",
        integration_type: "Service",
        primary_function: "CAD/BIM/Technical",
        input_type: "BIM",
        output_type: "Docs",
        pricing_model: "Enterprise",
        price_base_monthly: 1000.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Massive time save", "Standardization"],
        cons: ["Loss of control", "Black box"],
        efficiency_text: "Automates CD production completely.",
        workflow_text: "Cloud Service."
    },
    {
        id: "glyph",
        name: "Glyph",
        provider: "EvolveLAB",
        website_url: "https://www.evolvelab.io/glyph",
        description_short: "Automating documentation tasks in Revit.",
        description_long: "Plugin to automate the tedious tasks in Revit: tagging, dimensioning, sheet creation.",
        integration_type: "Integrated",
        host_software: "Revit",
        primary_function: "CAD/BIM/Technical",
        input_type: "BIM",
        output_type: "BIM",
        pricing_model: "Subscription",
        price_base_monthly: 50.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Task automation", "Time saving"],
        cons: ["Revit only", "Setup per project"],
        efficiency_text: "Eliminates click-heavy documentation.",
        workflow_text: "Revit Plugin."
    },
    {
        id: "vectorworks_ai",
        name: "Vectorworks AI",
        provider: "Vectorworks",
        website_url: "https://www.vectorworks.net/",
        description_short: "Integrated AI for stylization.",
        description_long: "Vectorworks integrated AI Visualizer for generating images inside the BIM environment.",
        integration_type: "Integrated",
        host_software: "Vectorworks",
        primary_function: "CAD/BIM/Technical",
        input_type: "3D Model",
        output_type: "Docs",
        pricing_model: "Subscription",
        price_base_monthly: 125.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 7,
        pros: ["Integrated CAD/BIM", "Mac friendly"],
        cons: ["Vectorworks only", "Less market share"],
        efficiency_text: "Integrated visualization.",
        workflow_text: "Native feature."
    },
    {
        id: "pype_autospecs",
        name: "Pype AutoSpecs",
        provider: "Autodesk",
        website_url: "https://pype.io/",
        description_short: "Scans spec manuals for submittals.",
        description_long: "AI that reads spec books and extracts the submittal register automatically.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "Docs",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 300.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Compliance safety", "Hours saved"],
        cons: ["Post-doc focused", "GC oriented"],
        efficiency_text: "Automates submittal log creation.",
        workflow_text: "Upload PDF -> Export Excel."
    },
    {
        id: "document_crunch",
        name: "Document Crunch",
        provider: "Document Crunch",
        website_url: "https://www.documentcrunch.com/",
        description_short: "AI review of contracts and specs.",
        description_long: "AI platform purpose-built for construction industry to review contracts and identify risks.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "Docs",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 100.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Risk mitigation", "Legal focus"],
        cons: ["Text heavy", "Niche"],
        efficiency_text: "Contract review speedup.",
        workflow_text: "Upload Doc -> AI Review."
    },
    {
        id: "bluebeam_revu",
        name: "Bluebeam Revu",
        provider: "Bluebeam",
        website_url: "https://www.bluebeam.com/",
        description_short: "Advanced PDF markup and coordination.",
        description_long: "Standard PDF tool for construction. Features visual search and batch processing.",
        integration_type: "Tool",
        primary_function: "Management",
        input_type: "Docs",
        output_type: "Docs",
        pricing_model: "Subscription",
        price_base_monthly: 30.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Firm", "Enterprise"],
        benchmark_rating: 10,
        pros: ["Powerful review", "Industry standard"],
        cons: ["PC only (mostly)", "Sub transition"],
        efficiency_text: "Digital redlining standard.",
        workflow_text: "Desktop App."
    },

    // --- 5. BIDDING & NEGOTIATION ---
    {
        id: "downtobid",
        name: "Downtobid",
        provider: "Downtobid",
        website_url: "https://downtobid.com/",
        description_short: "AI scans plans to create bid packages.",
        description_long: "AI that reviews construction plans to automatically identify scope and create bid packages for subs.",
        integration_type: "Service",
        primary_function: "Bidding/Finance",
        input_type: "Docs",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 150.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Scope detection", "Sub coverage"],
        cons: ["GC focused", "New"],
        efficiency_text: "Automated bid scoping.",
        workflow_text: "Web Platform."
    },
    {
        id: "smartbid",
        name: "SmartBid",
        provider: "ConstructConnect",
        website_url: "https://smartbid.co/",
        description_short: "Construction bid management.",
        description_long: "Bid management software for GCs.",
        integration_type: "Service",
        primary_function: "Bidding/Finance",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 200.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 7,
        pros: ["Sub database", "Organization"],
        cons: ["Legacy UI", "Cost"],
        efficiency_text: "Streamlined bid sending.",
        workflow_text: "Web Platform."
    },
    {
        id: "procore",
        name: "Procore",
        provider: "Procore",
        website_url: "https://www.procore.com/",
        description_short: "Construction management hub.",
        description_long: "The all-in-one platform for construction management.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 600.00, // Quote (expensive)
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Centralized hub", "Mobile app"],
        cons: ["High cost", "Complex"],
        efficiency_text: "Single source of truth.",
        workflow_text: "Cloud Platform."
    },
    {
        id: "alice_technologies",
        name: "Alice Technologies",
        provider: "Alice",
        website_url: "https://www.alicetechnologies.com/",
        description_short: "Generative construction scheduling.",
        description_long: "AI that simulates thousands of construction schedule options to find the most efficient path.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "Data",
        output_type: "Schedule",
        pricing_model: "Enterprise",
        price_base_monthly: 500.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Schedule optimization", "Recovery plans"],
        cons: ["Complex input", "Cost"],
        efficiency_text: "Reduces build time and risk.",
        workflow_text: "Web Platform."
    },
    {
        id: "togal_ai",
        name: "Togal.AI",
        provider: "Togal.AI",
        website_url: "https://www.togal.ai/",
        description_short: "AI-powered estimating and takeoff.",
        description_long: "Uses deep learning to automatically detect and measure room areas and walls from 2D plans.",
        integration_type: "Service",
        primary_function: "Bidding/Finance",
        input_type: "Docs",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 250.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Fast takeoffs", "98% accuracy claims"],
        cons: ["2D focus", "Cost"],
        efficiency_text: "Automated takeoff.",
        workflow_text: "Upload Plans -> AI Measure."
    },
    {
        id: "pelles_ai",
        name: "Pelles.ai",
        provider: "Pelles",
        website_url: "https://www.pelles.ai/",
        description_short: "AI for preconstruction.",
        description_long: "AI platform specifically for the preconstruction phase.",
        integration_type: "Service",
        primary_function: "Bidding/Finance",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 100.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm"],
        benchmark_rating: 7,
        pros: ["Precon focus", "Modern UI"],
        cons: ["Newer entrant", "Data needed"],
        efficiency_text: "Precon workflow automation.",
        workflow_text: "Web Platform."
    },
    {
        id: "join_build",
        name: "Join.build",
        provider: "Join",
        website_url: "https://join.build/",
        description_short: "Collaborative platform for VE decisions.",
        description_long: "Decision-making platform for OAC teams to track decisions and costs.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 300.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Transparency", "Visual tracking"],
        cons: ["Requires GC buy-in", "Cost"],
        efficiency_text: "Streamlines Value Engineering.",
        workflow_text: "Web Platform."
    },
    {
        id: "opencost",
        name: "OpenCost",
        provider: "CNCF",
        website_url: "https://www.opencost.io/",
        description_short: "Open source cost monitoring.",
        description_long: "Open source tool for monitoring cloud costs (Metaphor for open cost data).",
        integration_type: "Tool",
        primary_function: "Bidding/Finance",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Free",
        price_base_monthly: 0,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio"],
        benchmark_rating: 6,
        pros: ["Transparency", "Free"],
        cons: ["Dev focused", "Not construction native"],
        efficiency_text: "Budget tracking.",
        workflow_text: "Self-hosted."
    },

    // --- 6. CONSTRUCTION ADMIN ---
    {
        id: "disperse",
        name: "Disperse",
        provider: "Disperse",
        website_url: "https://www.disperse.io/",
        description_short: "Site photos to track work-in-place.",
        description_long: "Uses site photography to create digital twins and track progress against the schedule.",
        integration_type: "Service",
        primary_function: "Reality Capture",
        input_type: "Image",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 500.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 8,
        pros: ["Productivity data", "Actionable insights"],
        cons: ["Service heavy", "Cost"],
        efficiency_text: "Automated progress tracking.",
        workflow_text: "Site capture -> Cloud report."
    },
    {
        id: "openspace",
        name: "OpenSpace",
        provider: "OpenSpace",
        website_url: "https://www.openspace.ai/",
        description_short: "360-degree photo documentation.",
        description_long: "Passive video capture (hard hat cam) mapped to floor plans automatically using AI.",
        integration_type: "Service",
        primary_function: "Reality Capture",
        input_type: "Image",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 250.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Visual record", "Passive capture"],
        cons: ["Hardware cost", "Data storage"],
        efficiency_text: "Complete site documentation walk.",
        workflow_text: "Walk site -> Auto map."
    },
    {
        id: "plangrid",
        name: "PlanGrid",
        provider: "Autodesk",
        website_url: "https://www.plangrid.com/",
        description_short: "Mobile access to drawings.",
        description_long: "Field productivity software. The standard for viewing sheets on iPads.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Docs",
        output_type: "Docs",
        pricing_model: "Subscription",
        price_base_monthly: 40.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Firm", "Enterprise"],
        benchmark_rating: 9,
        pros: ["Real-time sync", "Field friendly"],
        cons: ["Tablet req.", "Cost stacking"],
        efficiency_text: "Paperless jobsite.",
        workflow_text: "iPad App."
    },
    {
        id: "newmetrix",
        name: "Newmetrix",
        provider: "Oracle",
        website_url: "https://www.oracle.com/construction-engineering/construction-intelligence-cloud-service/",
        description_short: "AI that predicts safety risks.",
        description_long: "AI that analyzes site photos to predict where safety incidents are likely to occur.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "Image",
        output_type: "Data",
        pricing_model: "Enterprise",
        price_base_monthly: 400.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Enterprise"],
        benchmark_rating: 8,
        pros: ["Safety focus", "Predictive"],
        cons: ["Data volume req.", "Oracle ecosystem"],
        efficiency_text: "Risk reduction.",
        workflow_text: "Cloud analysis."
    },
    {
        id: "newforma_konekt",
        name: "Newforma Konekt",
        provider: "Newforma",
        website_url: "https://www.newforma.com/",
        description_short: "AI-driven PIM for RFIs.",
        description_long: "Project Information Management. Organizes emails, RFIs, and submittals.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Docs",
        output_type: "Docs",
        pricing_model: "Enterprise",
        price_base_monthly: 200.00, // Quote
        usage_limit_per_month: -1,
        company_size_fit: ["Firm", "Enterprise"],
        benchmark_rating: 7,
        pros: ["Finding info", "Email search"],
        cons: ["Enterprise scale", "Legacy feel"],
        efficiency_text: "Search across all project data.",
        workflow_text: "Cloud Platform."
    },
    {
        id: "part3",
        name: "Part3",
        provider: "Part3",
        website_url: "https://www.part3.io/",
        description_short: "Automating RFIs and submittals.",
        description_long: "Platform designed by architects for CA. Automates creating logs and formatting docs.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Docs",
        output_type: "Docs",
        pricing_model: "Subscription",
        price_base_monthly: 200.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Studio", "Firm"],
        benchmark_rating: 8,
        pros: ["Saves massive time", "Architect focus"],
        cons: ["Niche", "Price"],
        efficiency_text: "CA admin automation.",
        workflow_text: "Web Platform."
    },
    {
        id: "trunk_tools",
        name: "Trunk Tools",
        provider: "Trunk",
        website_url: "https://www.trunktools.com/",
        description_short: "AI for construction incentives.",
        description_long: "AI based platform to manage labor incentives and payouts.",
        integration_type: "Service",
        primary_function: "Management",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 50.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm"],
        benchmark_rating: 7,
        pros: ["Field engagement", "Fintech angle"],
        cons: ["New approach", "Adoption"],
        efficiency_text: "Labor management.",
        workflow_text: "Mobile App."
    },
    {
        id: "civils_ai",
        name: "Civils.ai",
        provider: "Civils",
        website_url: "https://civils.ai/",
        description_short: "Construction data AI.",
        description_long: "AI for searching geotechnical reports and construction data.",
        integration_type: "Service",
        primary_function: "Data Interpretation",
        input_type: "Data",
        output_type: "Data",
        pricing_model: "Subscription",
        price_base_monthly: 50.00,
        usage_limit_per_month: -1,
        company_size_fit: ["Firm"],
        benchmark_rating: 7,
        pros: ["Data search", "Civil focus"],
        cons: ["Civil focus", "Niche"],
        efficiency_text: "Geotech data extraction.",
        workflow_text: "Web Platform."
    },
    {
        id: "manual_workflow",
        name: "Manual Workflow",
        provider: "Traditional",
        website_url: "#",
        description_short: "Traditional manual execution.",
        description_long: "The standard way of working without AI automation. Relies on human labor, standard software, and manual coordination.",
        integration_type: "Manual",
        primary_function: "Management",
        input_type: "Docs",
        output_type: "Docs",
        pricing_model: "Free",
        price_base_monthly: 0,
        usage_limit_per_month: -1,
        company_size_fit: ["Freelancer", "Studio", "Firm", "Enterprise"],
        benchmark_rating: 5,
        pros: ["Full Control", "No Learning Curve"],
        cons: ["Slow", "Laborious", "Error Prone"],
        efficiency_text: "Baseline efficiency.",
        workflow_text: "Human Labor."
    }
];

window.aiDatabase = aiDatabase; 
console.log("Database attached to window:", window.aiDatabase);// Helper to export if using modules, but for simple HTML import we let it be global
// window.aiDatabase = aiDatabase;